In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

sns.set_theme(style='whitegrid')
plt.rcParams['figure.figsize'] = (14, 6)

DATABASE_URL = 'postgresql://postgres:postgres@localhost:5432/sfotraffic'
engine  = create_engine(DATABASE_URL)

In [2]:
query = '''
    select
        activity_period_start_date as date
        ,sum(passenger_count) as total_passengers
    from
        passenger_traffic
    group by
        activity_period_start_date
    order by
        activity_period_start_date
'''

df = pd.read_sql(query, engine)

df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)
df = df.reset_index()

print(f'Time series shape: {df.shape}')
df.head()

Time series shape: (319, 2)

        date  total_passengers
0 1999-07-01           3976746
1 1999-08-01           3972694
2 1999-09-01           3341964
3 1999-10-01           3468846
4 1999-11-01           3145240

**Features Engineering**

In [10]:
import pandas as pd

def create_time_series_features(df: pd.DataFrame, target_col: str) -> pd.DataFrame:
    '''Creates (features) fro time series.'''

    df_feat = df.copy()

    df_feat['month'] = df_feat.index.month
    df_feat['quarter'] = df_feat.index.quarter
    df_feat['year'] = df_feat.index.year

    # Lags variables
    df_feat['lag_1M'] = df_feat[target_col].shift(1)
    df_feat['lag_3M'] = df_feat[target_col].shift(3)
    df_feat['lag_12M'] = df_feat[target_col].shift(12)

    # Rolling Means
    df_feat['rolling_mean_3M'] = df_feat[target_col].shift(1).rolling(window=3).mean()
    df_feat['rolling_mean_6M'] = df_feat[target_col].shift(1).rolling(window=6).mean()

    # Percentage Change
    df_feat['pct_change_1M'] = df_feat[target_col].shift(1).pct_change(1)

    df_feat.dropna(inplace=True)

    return df_feat

date_col = 'date' 
if date_col in df.columns:
    df[date_col] = pd.to_datetime(df[date_col])
    df.set_index(date_col, inplace=True)
    # (Month Start)
    df = df.asfreq('MS')

df_features = create_time_series_features(df=df, target_col='total_passengers').reset_index()

print(f'Original DataFrame size: {df.shape}')
print(f'Features DataFrame size: {df_features.shape}')
df_features.head()

Original DataFrame size: (319, 1)
Features DataFrame size: (307, 11)

        date  total_passengers  ...  rolling_mean_6M  pct_change_1M
0 2000-07-01           3996985  ...     3.266982e+06       0.111542
1 2000-08-01           3980297  ...     3.469624e+06       0.024857
2 2000-09-01           3327730  ...     3.678775e+06      -0.004175
3 2000-10-01           3335161  ...     3.684392e+06      -0.163949
4 2000-11-01           3303704  ...     3.674816e+06       0.002233

[5 rows x 11 columns]

**XGBOOST ML Model**

In [ ]:
import xgboost as xgb
import joblib
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error
from matplotlib.ticker import FuncFormatter
import os

# Data preparation
X = df_features.drop(columns=['total_passengers', 'date'])
y = df_features['total_passengers']

# Data spliting
X_train, X_test = X[:-12], X[-12:]
y_train, y_test = y[:-12], y[-12:]

print(f'Train DataFrame size: {X_train.shape[0]} months')
print(f'Test DataFrame size: {X_test.shape[0]} months')

# XGBoost model initialization
xgb_model = xgb.XGBRegressor(
    n_estimators=100
    ,learning_rate=0.05
    ,max_depth=3
    ,subsample=0.8
    ,random_state=42
)

# Model fiting
print("Trainind XGBooost...")
xgb_model.fit(X_train, y_train)

# XGBoost predictions
xgb_preds = xgb_model.predict(X_test)
xgb_preds_series = pd.Series(xgb_preds, index=y_test.index)

# XGBoost metrics
xgb_mae = mean_absolute_error(y_test, xgb_preds)
xgb_mape = mean_absolute_percentage_error(y_test, xgb_preds)

print("-" * 30)
print(f"XGBoost MAE: {xgb_mae:,.0f} пассажиров")
print(f"XGBoost MAPE: {xgb_mape:.2%}")
print("-" * 30)

# Model exporing
os.makedirs('../models', exist_ok=True)
model_path = '../models/xgboost_model.joblib'
joblib.dump(xgb_model, model_path)
print(f'Model exported: {model_path}')

# Visualization (Predictions Graph + Features Influence)

Train DataFrame size: 295 months
Test DataFrame size: 12 months
Trainind XGBooost...
------------------------------
XGBoost MAE: 220,792 пассажиров
XGBoost MAPE: 4.82%
------------------------------